---
title: "Initial R Code"
author: "Daniel Gardner"
date: "2024-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r warning=FALSE}
# Using BoolNet to load SBML data of Prostate Cancer
library(BoolNet)
Model<-loadSBML("Montagud2022_Prostate_Cancer.sbml")


# Creating list of genes and then data frame of their values (Initial values random)
Genes<-Model$genes
num.genes<-length(Genes)
Data<-data.frame(Genes=Genes,Values=sample(c(0,1),num.genes,replace = T),Rules=rep("none",num.genes))

# Creating separate boolean variables for every single gene
# Also adding in each Gene's boolean rule as a character string
for (i in 1:num.genes){
  assign(Genes[i],TRUE)
  Data$Rules[i]<-Model$interactions[[i]][3][[1]]
}

Input_Genes<-c('Acidosis','Androgen','Carcinogen','EGF','FGF','fused_event','Hypoxia','Nutrients','SPOP','TGFb')
```

# Initial test with a few steps

```{r}
# Number of Simulations
N<-500

# Number of discrete steps per simulation
K<-50

# List of stable state outputs
Stable_States<-list(rep(NA,N))


for(j in 1:N){
  
  # Defining Time series the same as the data
  Time_Series<-Data
  
  # Creating new random initial values, keeping initial values the same
  Time_Series$Values<-sample(c(0,1),num.genes,replace = T)
  Time_Series$Values[Time_Series$Genes %in% Input_Genes]<-rep(1,length(Input_Genes))

for (k in 1:K){
  # Current state
  Cur.Stat<-Time_Series$Values
  
  # Random ordering of Genes (Asynchronous)
  Rand_Genes<-sample(Genes)
  
  for (Gene in Rand_Genes){
    
    # Finding said gene's rule, current value, and whether it is being activated
    Rule<-Data[Data$Genes==Gene,3]
    Gen.act<-eval(parse(text=Rule))
    cur.val<-Data$Values[Data$Genes==Gene]
    
    # If activated and off, turn on
    if (Gen.act & cur.val==0){
      Time_Series$Values[Time_Series$Genes==Gene]<-1
      assign(Gene,TRUE)
    
  }
    # If repressed and on, turn off
    else if(!Gen.act & cur.val==1){
      Time_Series$Values[Time_Series$Genes==Gene]<-0
      assign(Gene,FALSE)
      
    # Else, do nothing
    
  }
    
  }
  
}

# Log the final state of the chain, as a stable state
  
Stable_States[[j]]<-Time_Series$Values

}

  length(unique(Stable_States))
```


